uploads = []
generated = []

[[outputs]]
id = "PkAbsr8cMq9-jfszORuYY"
uri = "file://exports/Paul-Ireifej-Monmouth-County-Public-Speaking.pptx"
type = "slides"
title = "Public Speaking — PowerPoint (5.1 MB)"

[[outputs]]
id = "nlUftyvPxbc0316Y8scnd"
uri = "file://exports/Paul-Ireifej-Monmouth-County-Active-Listening.pptx"
type = "slides"
title = "Active Listening — PowerPoint (7.2 MB)"
