// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/workshops/SignaturePrograms.tsx": () => import("../components/mockups/workshops/SignaturePrograms.tsx"),
  "./components/mockups/workshops/TimelineImpact.tsx": () => import("../components/mockups/workshops/TimelineImpact.tsx"),
  "./components/mockups/workshops/UpNextLogoWall.tsx": () => import("../components/mockups/workshops/UpNextLogoWall.tsx")
};
